// ASYNC
export const ASYNC_ACTION_START = "ASYNC_ACTION_START";
export const ASYNC_ACTION_FINISHED = "ASYNC_ACTION_FINISHED";
export const ASYNC_ACTION_ERROR = "ASYNC_ACTION_ERROR";

// AUTH
export const CHECK_USER_AUTH_STATE = "CHECK_USER_AUTH_STATE";
export const REGISTER_USER = "REGISTER_USER";
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";


// USER DETAILS
export const GET_USER_DETAILS = "GET_USER_DETAILS";
export const CHANGE_USER_IMAGE = "CHANGE_USER_IMAGE";
export const CHANGE_USER_DETAILS = "CHANGE_USER_DETAILS";

// POSTS
export const GET_POSTS = "GET_POSTS";
export const ADD_POSTS = "ADD_POSTS";
export const EDIT_POSTS = "EDIT_POSTS";
export const DELETE_POSTS = "DELETE_POSTS";


// COMMENTS
export const ADD_COMMENT = "ADD_COMMENT";
export const GET_COMMENTS = "GET_COMMENTS";
export const DELETE_COMMENT = "DELETE_COMMENT";

//LIKES
export const ADD_LIKES = "ADD_LIKES";
export const GET_LIKES = "GET_LIKES";
export const REMOVE_LIKES = "REMOVE_LIKES";


// LIVE UPDATE SECTION
// CHANGE USER DETAILS LIVE UPDATE
export const LIVE_UPDATE_CHANGE_USER_IMAGE = "LIVE_UPDATE_CHANGE_USER_IMAGE";
export const LIVE_UPDATE_CHANGE_USER_DETAILS = "LIVE_UPDATE_CHANGE_USER_DETAILS";

// POSTS LIVE UPDATE
export const LIVE_UPDATE_ADD_POSTS = "LIVE_UPDATE_ADD_POSTS";
export const LIVE_UPDATE_EDIT_POSTS = "LIVE_UPDATE_EDIT_POSTS";
export const LIVE_UPDATE_DELETE_POSTS = "LIVE_UPDATE_DELETE_POSTS";


// COMMENTS LIVE UPDATE
export const ADD_COMMENTS_LIVE_UPDATE = "ADD_COMMENTS_LIVE_UPDATE";
export const DELETE_COMMENTS_LIVE_UPDATE = "DELETE_COMMENTS_LIVE_UPDATE";

// LIKES LIVE UPDATE
export const ADD_LIKES_LIVE_UPDATE = "ADD_LIKES_LIVE_UPDATE";
export const REMOVE_LIKES_LIVE_UPDATE = "REMOVE_LIKES_LIVE_UPDATE";


